version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  orchestrator:
    build: ./orchestrator
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=info
    volumes:
      - ./orchestrator:/app

  # GPU worker will connect via Tailscale from Runpod
  # No local container needed - runs remotely

volumes:
  redis-data:

networks:
  default:
    name: rapid-studio-net
