services:
  redis:
    image: redis:7-alpine
    container_name: rapid-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  orchestrator:
    build: .
    container_name: rapid-orchestrator
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENVIRONMENT=development
      - GPU_WORKER_URL=http://157.157.221.29:8889
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./main.py:/app/main.py
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  redis-data:
